### ISSUE TITLE
Basic Usage Example

### ISSUE THREAD

**Issue by jgwhitebeard** [utopiantools/node-visca#2]
Hi. Great work. Thank you. Is there any chance you could provide a basic usage example for Visca over IP please?

**Comment by jeffmikels** [comment]
It really depends on your knowledge of node and your ability to read Javascript.

I'll look into writing up a description, though.

If you need to get rolling right away, I'm willing to do a quick zoom chat. What are you trying to use it for?

**Comment by bevand10** [comment]
Hi.

+1 for a brief example.

I'm more than happy with Node/JS. Have an existing node websocket client/server setup (socket.io) that's used to marshall cmd/ctrl messages between a few different web client apps and vision switchers (mainly Atem). I'm looking to integrate ptz control, already use the basic http interfaces available on <ip>/cgi-bin/ etc, but want to expand into VISCA-ip control to provide access to control features and acquire camera metadata that are missing from the cgi-bin interface.

I'm already using mdns-js to discover cameras (I have 5x SMTAV/PTZOptics 20x SDI G2 units) on the local LAN, so using your lib is the next step to gain full control over them.

**Comment by johncoles** [comment]
Just adding my desire for a basic example. I can read code and figure it out mostly but having a basic examples for:

- Connect to a camera
- Get camera status
- Set a position

Might be useful!

**Comment by bevand10** [comment]
Hi @johncoles .

I gave up waiting and wrote my own low-level tool https://github.com/bevand10/ptz-status

**Comment by johncoles** [comment]
Fair enough @bevand10,

I am thinking I will use ONVIF at the moment as it's all documented on their GitHub. I'd would love to move to Visca IP at some point.

**Comment by jeffmikels** [comment]
I'm actually not using this library myself. I wrote it as a basis for other people to build on if they found it valuable, but since I'm not using it, I don't have an example for you.

**Comment by bryce-seifert** [comment]
+1 For a basic getting started example in the docs, I think that would help save some time getting set-up
